name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"
          coverage: none
          tools: composer:v2

      - name: Validate composer
        run: composer validate --strict

      - name: Install dependencies
        run: composer update --prefer-dist --no-progress --no-interaction

      - name: Run CI test suite
        run: composer test:ci
